# Generated by Django 4.2.7 on 2023-11-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
            preserve_default=False,
        ),
    ]
